feat: 프로젝트 환경변수 설정
woowacourse-bot/discord-bot pull request #9
Opened 2023-10-27 11:27 UTC by cobocho

# What is this PR? 🔍

- `dotenv` install
- 환경변수 설정
- 변경사항 리드미 적용

2023-10-27 13:19 UTC, Ryan-Dia requested changes
수정 감사합니다. 고생하셨습니다. 👍

2023-10-27 13:19 UTC, Ryan-Dia commented on package.json
> +    "start": "node ./src/index.js",
p1 :  index.js 위치가 변경되어서 `main`도 변경해야될 것 같습니다.  따라서 `start`는 이전 값을 갖고 `main`을 "./src/index.js"로 해주시면 감사합니다.

2023-10-28 11:53 UTC, SWARVY reviewed
작업 수고많으셨어요 :)

2023-10-28 11:53 UTC, SWARVY commented on .gitignore
> +.env
EOL 빼먹은 것 수정해야할거같아요!

2023-10-28 11:58 UTC, jinyoung234 approved these changes
작업 고생 많으셨습니다 :)!

2023-10-28 11:58 UTC, jinyoung234 commented on src/index.js
> +// eslint-disable-next-line import/no-extraneous-dependencies
`eslint.json` 내 `rules`에 추가하면 어떨까 제안드립니다!

2023-10-28 12:08 UTC, jinyoung234 approved these changes
.

2023-10-28 12:08 UTC, jinyoung234 commented on README.md
32번 라인에 사진 `administractor`로 체크되어있는걸로 수정해야할거 같아여!

2023-10-28 12:22 UTC, merged